### PR TITLE
#200: The card number is alphanumeric now

### PR DESCRIPTION
**Pull request by IlyaMaier**
#200:
 - the card number is alphanumeric now
 - new migration in database

### CODE REVIEW

**Comment by codeguru42** [comment]
Overall this looks really good. I have a few things for you to fix. I will do a final review when I can get to my laptop.

**Comment by codeguru42** [comment]
Also, please edit your commit message to something more descriptive. Feel free to force push to this PR.

**Comment by IlyaMaier** [comment]
> Also, please edit your commit message to something more descriptive. Feel free to force push to this PR.

All done! Sorry, I got stuck with Git's rebase (it wanted me to merge changes), so I created a new PR.
PS.: if you know how to rebase it without merging, please write to me

**Comment by codeguru42** [comment]
> if you know how to rebase it without merging, please write to me

@IlyaMaier I'm not sure why you needed to rebase or merge. You should be able to commit the changes you make and push them to the same branch. This will update the PR. We'll continue with your new PR, but please let me know if you have any questions in the future. I'm pretty good with git and can help you figure it out.

**Pull request closed without merging**
