### PR TITLE
Navigate back press

### PR DESCRIPTION
**Pull request by jojonarte**
For  #334

### CODE REVIEW

**Comment by codeguru42** [comment]
Something still isn't quite right. The final pull request should only show commits that you made. It appears that your local `devel/android` branch is not the same as the `devel/android` in this main repo. To update it, do the following:

    git remote add bbct https://github.com/BaseballCardTracker/bbct.git
    git checkout devel/android
    git pull bbct devel/android

After you do this, you will need to rebase again. The steps are a little more complicated:

    git checkout navigate_back_press
    git rebase --onto devel/android 271f88d~
    git push -f

**Comment by jojonarte** [comment]
@codeguru42 after trying the steps above, I'm getting 2 conflicts but I don't see the conflict in thte files.

```
CONFLICT (content): Merge conflict in android/src/main/java/bbct/android/common/activity/BaseballCardList.java
Auto-merging android/src/androidTest/java/bbct/android/common/test/DatabaseUtil.java
CONFLICT (modify/delete): android/src/androidTest/java/bbct/android/common/navigation/test/NavigateUpFromBaseballCardDetailsTest.java deleted in HEAD and modified in adjust fragment stacks. Version adjust fragment stacks of android/src/androidTest/java/bbct/andr
oid/common/navigation/test/NavigateUpFromBaseballCardDetailsTest.java left in tree.
error: Failed to merge in the changes.
Patch failed at 0003 adjust fragment stacks
The copy of the patch that failed is found in: .git/rebase-apply/patch

```

**Comment by codeguru42** [comment]
@jojonarte Keep working on how to fix this branch. The final result needs to only have the commits with the tests for back press. It should not have any of my commits nor any of the commits for navigating up. If you don't want to redo the work on this branch, I suggest you look at the `git cherry-pick` command.

**Comment by jojonarte** [comment]
@codeguru42 okay, will update you soon.

**Comment by jojonarte** [comment]
I   think I should just redo it, I'm kind of confused with how to fix it. And I think redoing it would be faster in my opinion. I will do another pull request.

**Comment by codeguru42** [comment]
@jojonarte That is perfectly acceptable. Whatever works best for you.

**Pull request closed without merging**
